server:
  port: 80
#  servlet:
#    context-path: /pan

#thymeleaf===================================================================
#spring:
#  thymeleaf:
#    mode: HTML5
#    prefix: classpath:/

spring:
  mvc:
    view:
      prefix: /
      suffix: .html